### ISSUE TITLE
Getting rmagick error when setting sftp_url to https protocol

### ISSUE THREAD

**Issue by r00takaspin** [luan/carrierwave-ftp#30]
Hi, when I am setting sftp_url to https, for example
```
CarrierWave.configure do |config|
  config.sftp_host = "example.com"
  config.sftp_user = "someuser"
  config.sftp_folder = "images"
  config.sftp_url = "https://example.com"
  config.sftp_options = {
      :password => "xxxx",
      :port     => 22
  }
end
```

I am getting exception CarrierWave::ProcessingError. Here is trace:

```
carrierwave (0.8.0) lib/carrierwave/processing/rmagick.rb:343:in `rescue in manipulate!'
carrierwave (0.8.0) lib/carrierwave/processing/rmagick.rb:313:in `manipulate!'
carrierwave (0.8.0) lib/carrierwave/processing/rmagick.rb:190:in `resize_to_fill'
carrierwave (0.8.0) lib/carrierwave/uploader/processing.rb:85:in `block in process!'
carrierwave (0.8.0) lib/carrierwave/uploader/processing.rb:81:in `each'
carrierwave (0.8.0) lib/carrierwave/uploader/processing.rb:81:in `process!'
carrierwave (0.8.0) lib/carrierwave/uploader/callbacks.rb:18:in `block in with_callbacks'
carrierwave (0.8.0) lib/carrierwave/uploader/callbacks.rb:18:in `each'
carrierwave (0.8.0) lib/carrierwave/uploader/callbacks.rb:18:in `with_callbacks'
carrierwave (0.8.0) lib/carrierwave/uploader/cache.rb:122:in `cache!'
carrierwave (0.8.0) lib/carrierwave/uploader/versions.rb:236:in `block in cache_versions!'
carrierwave (0.8.0) lib/carrierwave/uploader/versions.rb:221:in `each'
carrierwave (0.8.0) lib/carrierwave/uploader/versions.rb:221:in `cache_versions!'
carrierwave (0.8.0) lib/carrierwave/uploader/callbacks.rb:18:in `block in with_callbacks'
carrierwave (0.8.0) lib/carrierwave/uploader/callbacks.rb:18:in `each'
carrierwave (0.8.0) lib/carrierwave/uploader/callbacks.rb:18:in `with_callbacks'
carrierwave (0.8.0) lib/carrierwave/uploader/cache.rb:122:in `cache!'
carrierwave (0.8.0) lib/carrierwave/uploader/versions.rb:179:in `recreate_versions!'
app/controllers/admin/photos_controller.rb:17:in `update'
```

Happens on OSX 10.11.3 and Ubuntu 12.04.

**Comment by r00takaspin** [comment]
Here is pull request #31

**Comment by luan** [comment]
I'm closing this in favor of your PR then @r00takaspin!
